on: push
name: ğŸš€ Deploy website on push
jobs:
  web-deploy:
    name: ğŸ‰ Deploy
    runs-on: ubuntu-latest
    steps:
    - name: ğŸšš Get latest codeactions/checkout@v2
      uses:

    - name: ğŸ“‚ Sync files
      uses: SamKirkland/FTP-Deploy-Action@4.2.0
      with:
        server: ftp.leadconcept.business
        username: ${{secrets.ftp_username}}
        password:
